# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geodesicFPOP_interface <- function(in_file_str, penalty_str, temp_file_str, container_str) {
    invisible(.Call('_geodesichange_geodesicFPOP_interface', PACKAGE = 'geodesichange', in_file_str, penalty_str, temp_file_str, container_str))
}

